import type { EN } from './strings-en';

export const DE: Record<keyof typeof EN, string> = {
  title: 'Pulse',
  subtitle: 'Merkt, wenn ein Batteriesensor still wird – hört nur zu und kostet keine Batterie.',
  tab_overview: 'Übersicht',
  tab_devices: 'Geräte',
  tab_notify: 'Mitteilungen',
  close: 'Schließen',
  more: 'Mehr',
  loading: 'Pulse lädt …',
  not_loaded:
    'Pulse ist noch nicht eingerichtet. Füge die Integration unter Einstellungen → Geräte & Dienste hinzu.',
  status_ok: 'Gut',
  status_learning: 'Lernt',
  status_watch: 'Beobachten',
  status_check: 'Prüfen',
  status_failed: 'Ausgefallen',
  ignored: 'Ignoriert',
  batteries: 'Batterien',
  nothing_due: 'Nichts fällig',
  last_change: 'Zuletzt gewechselt',
  zigbee: 'Zigbee2MQTT',
  zigbee_devices: 'Zigbee-Geräte',
  zigbee_sent: 'An Zigbee2MQTT geschickt',
  recipients: 'Empfänger',
  quiet: 'Ruhezeit',
  off: 'Aus',
  replaced: 'Batterie gewechselt',
  replaced_done: 'Wechsel eingetragen',
  later: 'Morgen erinnern',
  later_done: 'Pulse erinnert dich morgen',
  snoozed_until: 'Erinnert {when}',
  details: 'Details',
  ignore: 'Nicht überwachen',
  ignore_hint: 'Pulse lässt dieses Gerät in Ruhe.',
  ignored_done: '{name} wird nicht mehr überwacht',
  resume: 'Wieder überwachen',
  undo: 'Rückgängig',
  search: '{count} Geräte durchsuchen',
  search_one: '1 Gerät durchsuchen',
  group_by: 'Gruppieren nach {what}',
  group_area: 'Bereich',
  group_status: 'Status',
  group_none: 'Nicht gruppiert',
  col_last: 'Zuletzt gemeldet',
  no_area: 'Ohne Bereich',
  no_results: 'Kein Gerät passt zu „{query}“.',
  battery: 'Batterie',
  voltage: 'Spannung',
  battery_type: 'Typ',
  battery_count: 'Anzahl',
  chemistry: 'Art',
  chem_nimh: 'Akku (NiMH)',
  chem_alkaline: 'Alkaline',
  chem_lithium: 'Lithium',
  chem_unknown: 'Unbekannt',
  type_unknown: 'Nicht festgelegt',
  replaced_history: 'Batteriewechsel',
  never_replaced: 'Noch kein Wechsel eingetragen',
  monitoring: 'Überwachung',
  important: 'Wichtiges Gerät',
  important_hint:
    'Strengere Grenzen, ‚Prüfen‘ kommt sofort, Ausfälle auf Wunsch als kritische Mitteilung.',
  partner: 'Partnergerät',
  partner_hint:
    'Lösen meist zusammen aus, z. B. Schloss und Türkontakt. Bleibt eins still, merkt Pulse es früher.',
  partner_none: 'Keine',
  open_device: 'Geräteseite öffnen',
  just_now: 'gerade eben',
  minutes_ago: 'vor {n} Min.',
  hours_ago: 'vor {n} Std.',
  days_ago: 'vor {n} Tagen',
  day_ago: 'gestern',
  every_minutes: 'alle {n} Min.',
  every_hours: 'alle {n} Std.',
  every_days: 'alle {n} Tage',
  unknown: '—',
  today: 'heute',
  recipients_none: 'Kein Handy mit der Home-Assistant-App gefunden.',
  when: 'Wann benachrichtigen',
  level_failed: 'Ausgefallen',
  level_check: 'Prüfen',
  level_battery: 'Batterie bald leer',
  level_now: 'Sofort',
  level_daily: 'Täglich',
  level_off: 'Aus',
  times: 'Zeiten',
  summary_time: 'Tägliche Zusammenfassung',
  quiet_from: 'Von',
  quiet_to: 'Bis',
  quiet_hint: 'Mitteilungen in der Ruhezeit kommen danach. Kritische kommen immer durch.',
  special: 'Besonderes',
  critical: 'Kritische Mitteilungen',
  critical_hint: 'Lecksensoren, Rauchmelder, Schlösser – durchbrechen Lautlos und Fokus',
  arrive: 'Erst beim Heimkommen',
  recovered: 'Wenn ein Gerät wieder läuft',
  try_it: 'Ausprobieren',
  test: 'Testmitteilung senden',
  test_done: 'Testmitteilung an {count} Handy(s) geschickt',
  test_none: 'Kein Empfänger ausgewählt',
  summary_now: 'Zusammenfassung jetzt senden',
  summary_sent: 'Zusammenfassung geschickt',
  summary_empty: 'Gerade gibt es nichts zusammenzufassen',
  show_welcome: 'Willkommen zeigen',
  open_integration: 'Integration öffnen',
  whats_new_title: 'Neu in Pulse {version}',
  welcome_rhythm_title: 'Kennt jeden Takt',
  welcome_rhythm_text:
    'Wie oft sich jedes Gerät meldet, hat Pulse schon aus den letzten 10 Tagen gelernt.',
  welcome_listen_title: 'Hört nur zu',
  welcome_listen_text:
    'Pulse fragt nie ein Gerät ab. Das kostet keine Batterie und keinen Funkverkehr.',
  welcome_notify_title: 'Sagt rechtzeitig Bescheid',
  welcome_notify_text: 'Wichtiges sofort, alles andere einmal am Tag – mit Ruhezeit.',
  welcome_zigbee_title: 'Zigbee-Lebenszeichen',
  welcome_zigbee_text: 'Zigbee2MQTT hängt dann an jede Nachricht einen Zeitstempel.',
  continue: 'Weiter',
  version: 'Version {version}',
  today_cap: 'Heute',
  yesterday_cap: 'Gestern',
  zigbee_hint: 'Zeitstempel an jeder Nachricht – ohne Mehrverbrauch.',
  zigbee_active: 'Aktiv',
  zigbee_requested: 'Angefragt',
  zigbee_confirm_title: 'Zigbee-Lebenszeichen einschalten?',
  zigbee_confirm_text:
    'Pulse schaltet in Zigbee2MQTT „last_seen“ und „availability“ ein. Damit erkennt Pulse auch Meldungen ohne neuen Wert und merkt Funkabbrüche schneller.',
  zigbee_confirm_side:
    'Still gewordene Zigbee-Geräte erscheinen in Home Assistant dann als nicht verfügbar. Batteriegeräte senden dadurch nichts zusätzlich. Zurückstellen kannst du das jederzeit in Zigbee2MQTT unter Einstellungen.',
  zigbee_confirm_go: 'Einschalten',
  cancel: 'Abbrechen',
  level_unreliable: 'Akku – Prozent sagt wenig, Pulse achtet auf den Takt',
  replaced_undone: 'Wechsel zurückgenommen',
  filter_clear: 'Filter entfernen',
  filter_label: 'Nur: {what}',
  whats_new_all: 'Alle Neuerungen',
  replaced_now: 'Batteriewechsel eintragen',
  battery_none_low: 'Keine schwach',
  battery_low_one: '1 schwach',
  battery_low_many: '{count} schwach',
  hero_all: 'Alle {count} Geräte',
  hero_some: '{ok} von {total} Geräten',
  hero_some_short: '{ok} von {total}',
  hero_beat: 'schlagen im Takt.',
  hero_beat_short: 'im Takt.',
  hero_one: 'Dein einziges Gerät',
  hero_beat_one: 'schlägt im Takt.',
  hero_beat_off: 'ist still.',
  hero_learn1: 'Pulse',
  hero_learn2: 'lernt noch.',
  hero_none1: 'Noch keine',
  hero_none2: 'Batteriegeräte.',
  sent_silent_for: '{name} ist seit {span} still.',
  sent_silent_since: '{name} ist seit {day} still.',
  sent_battery: '{name} braucht bald eine neue Batterie.',
  sent_battery_low: '{name} braucht eine neue Batterie.',
  sent_unavailable: '{name} ist nicht erreichbar.',
  sent_partner: '{name} schweigt, obwohl {partner} aktiv ist.',
  sent_other: '{name}: {reason}',
  sent_more: 'Und {count} weitere.',
  sent_all_good: 'Alle melden sich wie gewohnt.',
  sent_learning: 'Pulse lernt gerade, wie oft sich jedes Gerät meldet.',
  span_minutes: '{n} Minuten',
  span_hours: '{n} Stunden',
  span_hour: '1 Stunde',
  span_days: '{n} Tagen',
  span_day: '1 Tag',
  yesterday: 'gestern',
  flag_silent: 'Seit {span} still',
  group_need: 'Braucht dich',
  group_watch: 'Im Blick',
  group_rhythm: 'Im Takt',
  group_learning: 'Lernt noch',
  monitor_head: '{count} Geräte · 7 Tage',
  monitor_head_one: '1 Gerät · 7 Tage',
  day_title: 'Dein Tag mit Pulse',
  day_to: 'An {names}',
  day_nobody: 'Noch kein Empfänger',
  status_battery: 'Batterie {level} %',
  new_battery: 'Neue Batterie',
  dh_silent: 'Still seit {span}.',
  dh_unavailable: 'Nicht erreichbar.',
  dh_partner: 'Schweigt, Partner aktiv.',
  dh_battery: 'Batterie bei {level} %.',
  dh_learning: 'Lernt noch.',
  dh_ok: 'Im Takt.',
  dh_ignored: 'Nicht überwacht.',
  dh_watch: 'Ungewohnt still.',
  detail_every: 'Meldet sich sonst {every}. Zuletzt {when}.',
  heartbeat_title: 'Herzschlag · 7 Tage',
  heartbeat_legend: 'Strich = Meldung · höher = mehrere',
  with_partner: 'Mit Partnergerät',
  partner_quiet: '{partner} meldet sich weiter – nur {name} schweigt.',
  partner_both: 'Beide melden sich wie gewohnt.',
  stat_changed: 'Gewechselt',
  welcome_head1: 'Pulse',
  welcome_head2: 'hört zu.',
  welcome_lead:
    'Jedes Batteriegerät hat einen Takt. Pulse kennt ihn – und merkt, wenn er aussetzt.',
  ignored_count: '{count} ignoriert',
  show_list: 'Liste zeigen',
  device_settings: 'Einstellungen',
  no_data_legend: 'Keine Daten – Pulse lief nicht',
  stat_rechargeable: 'Akku · ungenau',
  set_head: 'Pulse meldet sich um {time}.',
  set_quiet: 'Ruhe {start}–{end}.',
  set_no_quiet: 'Ohne Ruhezeit.',
  set_failed: 'Ausfälle',
  set_check: 'Auffälliges',
  set_battery: 'Batterien',
  set_group: '{names} {level}',
  set_level_now: 'sofort',
  set_level_daily: 'in der Zusammenfassung',
  set_level_off: 'nie',
  unit_volt: '{value} V',
  unit_millivolt: '{value} mV',
  unit_percent: '{value} %',
  battery_flag_low: 'Schwach',
  battery_flag_ok: 'OK',
  battery_count_type: '{count} × {type}',
  hour_label: '{h}:00',
  filter_empty: 'Kein Gerät in diesem Filter.',
  heartbeat_aria: '{count} Meldungen in {days} Tagen',
  replaced_undo_failed: 'Wechsel ließ sich nicht zurücknehmen',
  more_for: 'Mehr zu {name}',
  z2m_base: 'Zigbee2MQTT-Thema',
  z2m_base_hint:
    'Basisthema in MQTT, Standard ist zigbee2mqtt. Nur ändern, wenn dein Zigbee2MQTT ein anderes nutzt.',
  z2m_base_invalid:
    'Ungültiges Thema: nicht leer, ohne # und +, ohne Schrägstrich am Anfang oder Ende.',
  on: 'An',
  advanced: 'Erweitert',
  snooze_cancel: 'Erinnerung aufheben',
  snooze_cancelled: 'Erinnerung aufgehoben',
  read_only: 'Ändern können nur Admins.',
  levels_hint:
    'Ausgefallen: viel länger still als sonst oder nicht erreichbar. Prüfen: auffällig still oder Batterie unter 10 %. Beobachten bleibt im Panel.',
  recipients_hint: 'Neue Handys kommen automatisch dazu, bis du hier etwas änderst.',
  recovered_hint: 'Auch erkannte Batteriewechsel.',
  arrive_hint:
    'Mitteilungen warten, bis jemand der Gewählten zu Hause ist. Gilt für alle Empfänger.',
  persons_none: 'Keine Person in Home Assistant gefunden.',
  learning_hint: 'Lernt noch: braucht etwa 7 Meldungen, um den Takt zu kennen.',
  learning_one: 'Ein Gerät lernt Pulse noch kennen.',
  learning_many: '{count} Geräte lernt Pulse noch kennen.',
  pill_learning: 'Lernt noch',
  pill_waiting: 'Wartet',
  status_waiting: 'Wartet',
  dh_waiting: 'Wartet auf die erste Meldung.',
  sent_waiting: '{name} wartet auf die erste Meldung nach dem Batteriewechsel.',
  day_line_summary: '{time} Zusammenfassung',
  day_line_quiet: 'Ruhe {start} bis {end}',
  day_line_no_quiet: 'Ohne Ruhezeit',
};
