export const EN = {
  title: 'Pulse',
  subtitle: 'Notices when a battery sensor goes quiet – it only listens and costs no battery.',
  tab_overview: 'Overview',
  tab_devices: 'Devices',
  tab_notify: 'Notifications',
  close: 'Close',
  more: 'More',
  loading: 'Loading Pulse …',
  not_loaded: 'Pulse is not set up yet. Add the integration under Settings → Devices & services.',
  status_ok: 'Good',
  status_learning: 'Learning',
  status_watch: 'Watch',
  status_check: 'Check',
  status_failed: 'Failed',
  ignored: 'Ignored',
  batteries: 'Batteries',
  nothing_due: 'Nothing due',
  last_change: 'Last change',
  zigbee: 'Zigbee2MQTT',
  zigbee_hint: 'Timestamp on every message – no extra battery use.',
  zigbee_devices: 'Zigbee devices',
  zigbee_sent: 'Sent to Zigbee2MQTT',
  recipients: 'Recipients',
  quiet: 'Quiet hours',
  off: 'Off',
  replaced: 'Battery replaced',
  replaced_done: 'Change recorded',
  later: 'Remind tomorrow',
  later_done: 'Pulse will remind you tomorrow',
  snoozed_until: 'Reminds {when}',
  details: 'Details',
  ignore: "Don't monitor",
  ignore_hint: 'Pulse leaves this device alone.',
  ignored_done: '{name} is no longer monitored',
  resume: 'Monitor again',
  undo: 'Undo',
  search: 'Search {count} devices',
  search_one: 'Search 1 device',
  group_by: 'Group by {what}',
  group_area: 'area',
  group_status: 'status',
  group_none: 'No grouping',
  col_last: 'Last report',
  no_area: 'No area',
  no_results: 'No device matches “{query}”.',
  // Device sheet
  battery: 'Battery',
  voltage: 'Voltage',
  battery_type: 'Type',
  battery_count: 'Count',
  chemistry: 'Kind',
  chem_nimh: 'Rechargeable (NiMH)',
  chem_alkaline: 'Alkaline',
  chem_lithium: 'Lithium',
  chem_unknown: 'Unknown',
  type_unknown: 'Not set',
  replaced_history: 'Battery changes',
  never_replaced: 'No change recorded yet',
  monitoring: 'Monitoring',
  important: 'Important device',
  important_hint:
    'Stricter limits, “Check” arrives right away, failures as critical alerts if you like.',
  partner: 'Partner device',
  partner_hint:
    'Usually trigger together, e.g. lock and door contact. If one goes quiet, Pulse notices sooner.',
  partner_none: 'None',
  open_device: 'Open device page',
  just_now: 'just now',
  minutes_ago: '{n} min ago',
  hours_ago: '{n} h ago',
  days_ago: '{n} days ago',
  day_ago: 'yesterday',
  every_minutes: 'every {n} min',
  every_hours: 'every {n} h',
  every_days: 'every {n} days',
  unknown: '—',
  today: 'today',
  // Notifications
  recipients_none: 'No phone with the Home Assistant app found.',
  when: 'When to notify',
  level_failed: 'Failed',
  level_check: 'Check',
  level_battery: 'Battery running low',
  level_now: 'Right away',
  level_daily: 'Daily',
  level_off: 'Off',
  times: 'Times',
  summary_time: 'Daily summary',
  quiet_from: 'From',
  quiet_to: 'Until',
  quiet_hint:
    'Notifications in quiet hours are delivered afterwards. Critical ones always come through.',
  special: 'Special cases',
  critical: 'Critical alerts',
  critical_hint: 'Leak sensors, smoke detectors, locks – break through silent mode and focus',
  arrive: 'Only when someone is home',
  recovered: 'When a device is back',
  try_it: 'Try it',
  test: 'Send test notification',
  test_done: 'Test sent to {count} phone(s)',
  test_none: 'No recipient selected',
  summary_now: 'Send summary now',
  summary_sent: 'Summary sent',
  summary_empty: 'Nothing to summarize right now',
  show_welcome: 'Show welcome',
  open_integration: 'Integration settings',
  // Welcome
  whats_new_title: 'New in Pulse {version}',
  welcome_rhythm_title: 'Knows every rhythm',
  welcome_rhythm_text:
    'Pulse has already learned from the last 10 days how often each device reports.',
  welcome_listen_title: 'Only listens',
  welcome_listen_text: 'It never queries a device. That costs no battery and no radio traffic.',
  welcome_notify_title: 'Tells you in time',
  welcome_notify_text:
    'Important things right away, everything else once a day – with quiet hours.',
  welcome_zigbee_title: 'Zigbee signs of life',
  welcome_zigbee_text: 'Let Zigbee2MQTT add a timestamp to every message.',
  continue: 'Continue',
  version: 'Version {version}',
  today_cap: 'Today',
  yesterday_cap: 'Yesterday',
  zigbee_active: 'Active',
  zigbee_requested: 'Requested',
  zigbee_confirm_title: 'Turn on Zigbee signs of life?',
  zigbee_confirm_text:
    'Pulse turns on “last_seen” and “availability” in Zigbee2MQTT. Pulse then also notices reports without a new value and spots radio dropouts sooner.',
  zigbee_confirm_side:
    'Zigbee devices that have gone quiet then show up as unavailable in Home Assistant. Battery devices don’t send anything extra. You can change this back any time in the Zigbee2MQTT settings.',
  zigbee_confirm_go: 'Turn on',
  cancel: 'Cancel',
  level_unreliable: 'Rechargeable – percentage says little, Pulse watches the rhythm',
  replaced_undone: 'Change removed',
  filter_clear: 'Remove filter',
  filter_label: 'Only: {what}',
  whats_new_all: 'All changes',
  replaced_now: 'Record battery change',
  battery_none_low: 'None low',
  battery_low_one: '1 low',
  battery_low_many: '{count} low',
  hero_all: 'All {count} devices',
  hero_some: '{ok} of {total} devices',
  hero_some_short: '{ok} of {total}',
  hero_beat: 'are in rhythm.',
  hero_beat_short: 'in rhythm.',
  hero_one: 'Your only device',
  hero_beat_one: 'is in rhythm.',
  hero_beat_off: 'is silent.',
  hero_learn1: 'Pulse',
  hero_learn2: 'is learning.',
  hero_none1: 'No battery',
  hero_none2: 'devices yet.',
  sent_silent_for: '{name} has been silent for {span}.',
  sent_silent_since: '{name} has been silent since {day}.',
  sent_battery: '{name} needs a new battery soon.',
  sent_battery_low: '{name} needs a new battery.',
  sent_unavailable: '{name} is unreachable.',
  sent_partner: '{name} is silent while {partner} is active.',
  sent_other: '{name}: {reason}',
  sent_more: 'And {count} more.',
  sent_all_good: 'Every device checks in as usual.',
  sent_learning: 'Pulse is learning how often each device checks in.',
  span_minutes: '{n} minutes',
  span_hours: '{n} hours',
  span_hour: '1 hour',
  span_days: '{n} days',
  span_day: '1 day',
  yesterday: 'yesterday',
  flag_silent: 'Silent for {span}',
  group_need: 'Needs you',
  group_watch: 'Keeping an eye on',
  group_rhythm: 'In rhythm',
  group_learning: 'Learning',
  monitor_head: '{count} devices · 7 days',
  monitor_head_one: '1 device · 7 days',
  day_title: 'Your day with Pulse',
  day_to: 'To {names}',
  day_nobody: 'No recipient yet',
  status_battery: 'Battery {level}%',
  new_battery: 'New battery',
  dh_silent: 'Silent for {span}.',
  dh_unavailable: 'Unreachable.',
  dh_partner: 'Silent, partner active.',
  dh_battery: 'Battery at {level}%.',
  dh_learning: 'Still learning.',
  dh_ok: 'In rhythm.',
  dh_ignored: 'Not monitored.',
  dh_watch: 'Unusually quiet.',
  detail_every: 'Usually checks in {every}. Last report {when}.',
  heartbeat_title: 'Heartbeat · 7 days',
  heartbeat_legend: 'Tick = report · taller = several',
  with_partner: 'With partner device',
  partner_quiet: '{partner} keeps checking in – only {name} is silent.',
  partner_both: 'Both check in as usual.',
  stat_changed: 'Replaced',
  welcome_head1: 'Pulse',
  welcome_head2: 'listens.',
  welcome_lead: 'Every battery device has a rhythm. Pulse knows it – and notices when it skips.',
  ignored_count: '{count} ignored',
  show_list: 'Show list',
  device_settings: 'Settings',
  no_data_legend: 'No data – Pulse wasn’t running',
  stat_rechargeable: 'Rechargeable · rough',
  set_head: 'Pulse checks in at {time}.',
  set_quiet: 'Quiet {start}–{end}.',
  set_no_quiet: 'No quiet hours.',
  set_failed: 'failures',
  set_check: 'anomalies',
  set_battery: 'batteries',
  set_group: '{names} {level}',
  set_level_now: 'right away',
  set_level_daily: 'in the summary',
  set_level_off: 'never',
  unit_volt: '{value} V',
  unit_millivolt: '{value} mV',
  unit_percent: '{value}%',
  battery_flag_low: 'Low',
  battery_flag_ok: 'OK',
  battery_count_type: '{count} × {type}',
  hour_label: '{h}:00',
  filter_empty: 'No device in this filter.',
  heartbeat_aria: '{count} reports in {days} days',
  replaced_undo_failed: 'Could not undo the change',
  more_for: 'More for {name}',
  z2m_base: 'Zigbee2MQTT topic',
  z2m_base_hint:
    'MQTT base topic, default is zigbee2mqtt. Only change it if your Zigbee2MQTT uses a different one.',
  z2m_base_invalid: 'Invalid topic: not empty, no # or +, no slash at the start or end.',
  // Second round
  on: 'On',
  advanced: 'Advanced',
  snooze_cancel: 'Cancel reminder',
  snooze_cancelled: 'Reminder cancelled',
  read_only: 'Only admins can make changes.',
  levels_hint:
    'Failed: silent much longer than usual or unreachable. Check: unusually quiet or battery below 10%. Watch stays in the panel.',
  recipients_hint: 'New phones are added automatically until you change something here.',
  recovered_hint: 'Also detected battery changes.',
  arrive_hint:
    'Notifications wait until one of the selected people is home. Applies to all recipients.',
  persons_none: 'No person found in Home Assistant.',
  learning_hint: 'Still learning: needs about 7 reports to know the rhythm.',
  learning_one: 'Pulse is still getting to know 1 device.',
  learning_many: 'Pulse is still getting to know {count} devices.',
  pill_learning: 'Learning',
  pill_waiting: 'Waiting',
  status_waiting: 'Waiting',
  dh_waiting: 'Waiting for the first report.',
  sent_waiting: '{name} is waiting for its first report after the battery change.',
  day_line_summary: 'Summary {time}',
  day_line_quiet: 'Quiet {start} to {end}',
  day_line_no_quiet: 'No quiet hours',
};
